### PR TITLE
feat: added typography and lists components

### PR DESCRIPTION
**Pull request by bhargaviRdy**
Made different types of lists and text styles.
Look into 
https://vibe-ui-8l90yl2st-bhargavirdy.vercel.app/docs/text-utilities.html
https://vibe-ui-8l90yl2st-bhargavirdy.vercel.app/docs/lists.html for changes

### CODE REVIEW

**Review by Bhakti199 — APPROVED** [review]
everything looks cool, good to merge

**Review by Manju-sree — COMMENTED** [review]
try to align items center in text utilities and try to remove spaces in iframe. rest all looks fine

**Comment by bhargaviRdy** [comment]
> try to align items center in text utilities and try to remove spaces in iframe. rest all looks fine

made the changes, please have a look
https://vibe-ui-git-list-bhargavirdy.vercel.app/docs/text-utilities.html

**Review by Manju-sree — APPROVED** [review]
now it's look fine, good to merge

**Pull request merged**
